@startuml
DTSX字段重构软件 -> ETL管理库: 获取业务库、平台库信息
DTSX字段重构软件 -> ETL管理库: 获取定义抽取表信息
DTSX字段重构软件 -> 业务库: 根据抽取表信息获取字段信息
DTSX字段重构软件 -> ODS库: 根据抽取表信息获取字段信息
DTSX字段重构软件 -> DTSX字段重构软件: 比对字段冲突
DTSX字段重构软件 -> 文件系统: 遍历DTSX文件替换长度冲突内容

@enduml